Refactor/network module
KritikHub/MovieMania pull request #3
Opened 2023-11-05 17:04 UTC by KritikHub

2023-11-05 17:06 UTC, KritikHub commented
@JustManish Please review the latest changes in the branch.

2023-11-06 13:27 UTC, JustManish requested changes

2023-11-06 13:27 UTC, JustManish commented on SwiftUiMovieDb/Network/APIKey.swift
> +        return "3492e734e03e243d1f8b59388a7b1bb2"
let's store this in xcconfig file and read from that.

2023-11-06 13:27 UTC, JustManish commented on SwiftUiMovieDb/Network/APIService.swift
> +                             headers: [String: String]? = nil,
why headers argument, it's not needed can get from URN itself.

2023-11-06 13:27 UTC, JustManish commented on SwiftUiMovieDb/Network/APIService.swift
> +            if let error = error {
guard will be more suitable here.

2023-11-06 13:27 UTC, JustManish commented on SwiftUiMovieDb/Protocol/DescriptiveErrorType.swift
> +struct MDBErrorConstants {
This struct is not needed let's create localization file and move all the strings in it and directly use it in below enum.

2023-11-06 13:27 UTC, JustManish commented on SwiftUiMovieDb/Views/MovieBackdropCard.swift
> +@ViewBuilder
do we really need to annotate it with @Viewbuilder ?

2023-11-06 13:27 UTC, JustManish commented on SwiftUiMovieDb/Views/MovieBackdropCard.swift
> +    Image("PosterImagePlaceholder")
Let's create an enum to manage all the icon or image asset to be typesafe and less errorprone, avoid using String constant's.

2023-11-06 13:27 UTC, JustManish commented on SwiftUiMovieDb/Views/MoviePosterCard.swift
> +    Image("PosterImagePlaceholder")
same here

2023-11-06 13:27 UTC, JustManish commented on SwiftUiMovieDb/Views/MoviePosterCard.swift
> +@ViewBuilder
do we really need @ViewBuilder annotation here ? think about it and let me know why not ?

2023-11-23 19:15 UTC, closed without merging